FROM python:3.7.4-slim-stretch
RUN apt-get update && apt-get install -y gcc libc-dev
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN python3 -m pip install --no-cache-dir -r requirements.txt && python3 -m pip install --no-cache-dir uwsgi
COPY . .
RUN chown -R www-data:www-data /usr/src/app
USER www-data
EXPOSE 8080
CMD ["uwsgi", "--ini", "uwsgi.ini"]
